// Правила сетевого блокировщика: один список на обе платформы.
//
// Вынесены из adblock.rs, потому что у Windows и macOS разные движки блокировки —
// перехват WebResourceRequested там и декларативный WKContentRuleList здесь, —
// но список рекламных адресов обязан быть общим. Две копии разошлись бы на первой
// же охоте разведчиком (features/adblock/net-probe.ts), и одна платформа тихо
// осталась бы со старым снимком.
//
// Модуль без cfg сознательно: он состоит из одних констант и на не-Windows
// компилируется в ничто, если им никто не пользуется.

/// Проверяется первым и всегда побеждает приметы. localhost обязателен:
/// на нём живёт ipc.localhost, его блокировка убьёт приложение целиком.
pub const ALLOW_HOSTS: &[&str] = &[
    "localhost",
    "anilist.co",
    "kodikplayer.com",
    "kodikres.com",
    "kodik-api.com",
    "solodcdn.com",
    "shikimori.one",
    "shikimori.io",
    "shikimori.rip",
    "anime365.ru",
    "smotret-anime.online",
    "animethemes.moe",
    "githubusercontent.com",
    "fonts.googleapis.com",
    "fonts.gstatic.com",
    "gstatic.com",
    "jsdelivr.net",
];

/// Собрано живой охотой 02.08.2026, не из чужих списков. Сравнение — целиком
/// или поддомен.
pub const AD_HOSTS: &[&str] = &[
    // — цепочка плеера
    "buzzoola.com",
    "bracdn.online",
    "snsv.ru",
    "sapfir.tv",
    "moviead55.ru",
    "21wiz.com",
    "bidster.net",
    "vidalak.com",
    "traffmovie.com",
    "flyroll.ru",
    "surfy.space",
    "punchmedia.ru",
    "moe.video",
    "xcec.ru",
    "adseedtech.com",
    "betweendigital.com",
    "ufouxbwn.com",
    "adstag0102.xyz",
    "ctrltech.ai",
    "agenteimmobiliare.info",
    "voxexchange.io",
    "mc.yandex.ru",
    "mc.yandex.md",
    "an.yandex.ru",
    "adfox.ru",
    // — биржи самого AniList
    "vntsm.com",
    "vntsm.io",
    "venatusmedia.com",
    "rapidedge.io",
    "doubleclick.net",
    "googlesyndication.com",
    "fundingchoicesmessages.google.com",
    "google-analytics.com",
    "googletagmanager.com",
    "ccgateway.net",
    "atmtd.com",
    "fastclick.net",
    "amazon-adsystem.com",
    "criteo.com",
    "rubiconproject.com",
    "pubmatic.com",
    "3lift.com",
    "adnxs.com",
    "openx.net",
    "smartadserver.com",
    "sharethrough.com",
    "bidswitch.net",
    "yellowblue.io",
    "onetag-sys.com",
    "tappx.com",
    "presage.io",
    "aniview.com",
    "id5-sync.com",
    "rlcdn.com",
    "casalemedia.com",
    "media.net",
    "adform.net",
    "360yield.com",
    "gumgum.com",
    "the-ozone-project.com",
    "bids.ws",
    "smilewanted.com",
    "richaudience.com",
    "inmobi.com",
    "loopme.me",
    "admanmedia.com",
    "creativecdn.com",
    "adsrvr.org",
    "stackadapt.com",
    "quantserve.com",
    "crwdcntrl.net",
    "everesttech.net",
    "bidr.io",
    "dotomi.com",
    "outbrain.com",
    "zemanta.com",
    "yieldmo.com",
    "1rx.io",
    "contextweb.com",
    "lijit.com",
    "sonobi.com",
    "smaato.net",
    "bidmatic.io",
    "hadronid.net",
    "ad-delivery.net",
    "dnacdn.net",
    "script.ac",
    "clean.gg",
    "4dex.io",
    "amxrtb.com",
    "a-mx.com",
    "a-mo.net",
    "amx1.net",
    "deepintent.com",
    "ipredictive.com",
    "socdm.com",
    "eskimi.com",
    "chocolateplatform.com",
    "ymmobi.com",
    "syncingbridge.com",
    "measureadv.com",
    "company-target.com",
    "mediagotechnology.com",
    "lunamedia.live",
    "adx.opera.com",
    "fwmrm.net",
    "analytics.yahoo.com",
    "omnitagjs.com",
    "ssp.disqus.com",
];

/// Второй слой: домен победителя аукциона меняет и номер, и поддомен от запуска
/// к запуску, а стандарты видеорекламы в адресе — нет.
pub const AD_PATTERNS: &[&str] = &[
    "/vast",
    "vast.php",
    "vast?",
    "vpaid",
    "/ads/adfox",
    "/openrtb",
    "/prebid",
    "usersync",
    "user-sync",
    "user_sync",
    "cookie_sync",
    "cookie-sync",
    "/cksync",
    "/getuid",
    "/setuid",
];
